# Esse workflow realiza o check de lint do python, utilizando o Black

name: Black Lint Check

# Controls when the workflow will run
on:
  # Aciona em eventos de push e pr's para a main.
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]
    types: ["opened"]

  # Rodar o workflow manualmente
  workflow_dispatch:

jobs:
  black-lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        
      - name: Installing dependencies
        run: uv sync --locked --all-extras --dev

      - name: Running Black lint check
        run: uv run black --check .
